### ISSUE TITLE
Mention `jq` dependency in docs. 

### ISSUE THREAD

**Issue by maxmynter** [zenml-io/mlstacks#126]
Hey `mlstacks` team

I encountered an issue with the AWS Quickstart example provided in your documentation. It was caused by a missing dependency, [`jq`](https://jqlang.github.io/jq/).

## Issue Description
The scripts `get_cluster_info.sh`, `get_cluster_token.sh` and possibly others as well rely on `jq` for JSON processing. The dependency on `jq` is not mentioned in the docs. 

Without the`jq` installed, the `mlstacks deploy -f quickstart_stack.yaml` command from the AWS quickstart in the docs fails with a  cryptic error message.

```bash
RuntimeError: 
Error: Unexpected External Program Results

  with data.external.get_cluster_info,
  on eks.tf line 248, in data "external" "get_cluster_info":
 248:   program = ["bash", "${path.module}/get_cluster_info.sh"]

The data source received unexpected results after executing the program.

Program output must be a JSON encoded map of string keys and string values.

If the error is unclear, the output can be viewed by enabling Terraform's
logging at TRACE level. Terraform documentation on logging:
https://www.terraform.io/internals/debugging

Program: /opt/homebrew/bin/bash
Result Error: unexpected end of JSON input

Error: Unexpected External Program Results

  with data.external.get_cluster_auth,
  on eks.tf line 260, in data "external" "get_cluster_auth":
 260:   program = ["bash", "${path.module}/get_cluster_token.sh"]

The data source received unexpected results after executing the program.

Program output must be a JSON encoded map of string keys and string values.

If the error is unclear, the output can be viewed by enabling Terraform's
logging at TRACE level. Terraform documentation on logging:
https://www.terraform.io/internals/debugging

Program: /opt/homebrew/bin/bash
Result Error: unexpected end of JSON input
```

These errors do not immediately indicate the absence of jq as the cause. However, manually executing the scripts revealed a more explicit error:

```bash
echo '{}' | bash get_cluster_info.sh  
get_cluster_info.sh: line 3: jq: command not found
get_cluster_info.sh: line 26: jq: command not found
```

## Suggestions
- Mention the `jq` dependency in the docs.
- Maybe there is a way to propagate these more indicative error messages.

**Comment by strickvl** [comment]
Thanks. For our understanding, what OS were you running this from / on?

**Comment by strickvl** [comment]
Ok got it. I'll update the docs appropriately. I guess all the machines where we test this has it pre-installed. Thanks for catching it!

**Comment by strickvl** [comment]
Merged in now. Thanks again!
