### ISSUE TITLE
Change AWS resources names in AWS Quickstarts in docs to not include underscores

### ISSUE THREAD

**Issue by maxmynter** [zenml-io/mlstacks#127]
Hey `mlstacks` team, 

I am working through the Quickstarts in the documentation and encountered an issue with the namings of the resources. Namely, AWS throws an error when it contains underscores:
```bash 
RuntimeError: 
Error: validating S3 Bucket (zenml-quickstart_s3_bucket) name: 
only lowercase alphanumeric characters and hyphens allowed in 
"zenml-quickstart_s3_bucket"

  with aws_s3_bucket.zenml-artifact-store[0],
  on s3.tf line 2, in resource "aws_s3_bucket" 
"zenml-artifact-store":
   2: resource "aws_s3_bucket" "zenml-artifact-store" {
```

## Suggestion
Adapt the two example `.yaml` files to use `-` instead of `_` in the name properties. 

I can make a PR for this, if there is nothing I have overlooked.

**Comment by strickvl** [comment]
Thank you for this. Just replacing with hyphens would be fine, and a PR would be welcomed!

**Comment by strickvl** [comment]
Thanks for the quick fix!
